version: '3'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./tooling/postgres:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:${REDIS_VERSION}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379

  bitcoin-lib-grpc:
    image: ghcr.io/ledgerhq/bitcoin-lib-grpc:${BITCOIN_LIB_GRPC_VERSION}
    environment:
      BITCOIN_HOST: ${BITCOIN_LIB_GRPC_HOST}
      BITCOIN_PORT: ${BITCOIN_LIB_GRPC_PORT}
    ports:
      - ${BITCOIN_LIB_GRPC_PORT}:${BITCOIN_LIB_GRPC_PORT}

  bitcoin-keychain:
    image: ghcr.io/ledgerhq/bitcoin-keychain:${BITCOIN_KEYCHAIN_VERSION}
    environment:
      BITCOIN_KEYCHAIN_HOST: ${BITCOIN_KEYCHAIN_HOST}
      BITCOIN_KEYCHAIN_PORT: ${BITCOIN_KEYCHAIN_PORT}
      BITCOIN_KEYCHAIN_LOG_LEVEL: ${BITCOIN_KEYCHAIN_LOG_LEVEL}
      BITCOIN_KEYCHAIN_JSON_LOGS: ${BITCOIN_KEYCHAIN_JSON_LOGS}
      BITCOIN_HOST: ${BITCOIN_LIB_GRPC_HOST}
      BITCOIN_PORT: ${BITCOIN_LIB_GRPC_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL: ${REDIS_SSL}
      REDIS_DB: ${BITCOIN_KEYCHAIN_REDIS_DB}
    depends_on:
      - redis
      - bitcoin-lib-grpc
    ports:
      - ${BITCOIN_KEYCHAIN_PORT}:${BITCOIN_KEYCHAIN_PORT}
