apiVersion: v2
name: keychain
description: Bitcoin Keychain chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.4.0"
dependency:
- name: redis
  version: "14.6.2"
  repository: "https://charts.bitnami.com/bitnami"
